CREATE TABLE lfa1_general (
    LIFNR VARCHAR(20),
    KTOKK VARCHAR(10),
    NAME1 VARCHAR(120),
    LAND1 VARCHAR(5),
    REGIO VARCHAR(10),
    ORT01 VARCHAR(80),
    PSTLZ VARCHAR(20),
    STRAS VARCHAR(120),
    STCD1 VARCHAR(20),
    TELF1 VARCHAR(40),
    SPERR BOOLEAN,
    LOEVM BOOLEAN
);

CREATE TABLE lfb1_company (
    LIFNR VARCHAR(20),
    BUKRS VARCHAR(10),
    AKONT VARCHAR(20),
    ZTERM VARCHAR(10),
    ZWELS VARCHAR(20),
    XZEMP BOOLEAN
);
