CREATE TABLE mara_core (
    MATNR VARCHAR(40),
    BISMT VARCHAR(40),
    MTART VARCHAR(10),
    MATKL VARCHAR(20),
    MEINS VARCHAR(10),
    BRGEW DECIMAL(10,3),
    NTGEW DECIMAL(10,3),
    GEWEI VARCHAR(5),
    ERSDA DATE,
    XCHPF BOOLEAN,
    LVORM BOOLEAN
);

CREATE TABLE makt_text (
    MATNR VARCHAR(40),
    SPRAS VARCHAR(2),
    MAKTX VARCHAR(120),
    MAKTG VARCHAR(120),
    SEARCH_TEXT VARCHAR(120)
);
