CREATE TABLE kna1_general (
    KUNNR VARCHAR(20),
    NAME1 VARCHAR(120),
    LAND1 VARCHAR(5),
    ORT01 VARCHAR(80),
    TELF1 VARCHAR(40)
);

CREATE TABLE knvv_sales (
    KUNNR VARCHAR(20),
    VKORG VARCHAR(10),
    VTWEG VARCHAR(10),
    SPART VARCHAR(10),
    KDGRP VARCHAR(10),
    BZIRK VARCHAR(10),
    VSBED VARCHAR(10),
    INCO1 VARCHAR(10),
    INCO2 VARCHAR(80),
    WAERS VARCHAR(5),
    ZTERM VARCHAR(10),
    KALKS VARCHAR(10),
    PLTYP VARCHAR(10)
);
