CREATE TABLE eina_header (
    INFNR VARCHAR(20),
    LIFNR VARCHAR(20),
    MATNR VARCHAR(40),
    LOEKZ BOOLEAN,
    URZLA VARCHAR(20)
);

CREATE TABLE eine_org (
    INFNR VARCHAR(20),
    EKORG VARCHAR(10),
    WERKS VARCHAR(10),
    ESOKZ VARCHAR(5),
    NETPR DECIMAL(14,2),
    WAERS VARCHAR(5),
    PEINH DECIMAL(14,2),
    MINBM DECIMAL(14,2),
    APLFZ INTEGER,
    INCO1 VARCHAR(10),
    INCO2 VARCHAR(80),
    BPRME VARCHAR(10)
);
